server:
  port: 20001
spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30 #续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 10 #续约更新时间间隔（默认30秒）
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
    enabled: true
